[package]
name = "dice-calc-lib"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0"
itertools = "0.10"
num = { version = "0.4", features = ["default", "num-bigint"] }
parse-display = "0.8"
rand = "0.8"
thiserror = "1.0"
winnow = "0.4"
